---
name: Cron

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'

concurrency:
  group: ${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  puppet:
    name: Puppet
    uses: voxpupuli/gha-puppet/.github/workflows/beaker.yml@v3
